/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.SoftwarePR.AgendaDeTarefas.InterfaceAlteracao;

import br.com.SoftwarePR.AgendaDeTarefas.Banco.conexaoBanco;
import br.com.SoftwarePR.AgendaDeTarefas.Construtor.construtorCriarTarefa;
import br.com.SoftwarePR.AgendaDeTarefas.Interface.interfaceMenuTarefa;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo
 */
public class interfaceAlterarDadosDaTarefa extends javax.swing.JFrame {

    /**
     * Creates new form interfaceAlterarDadosDaTarefa
     */
    int ID;
    int STATUS;
    String NOME;
    String DESCRICAO;
    String DATA;
    
    public interfaceAlterarDadosDaTarefa() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(26,30,36));
        PainelPrincipal.setBackground(new Color(26,30,36));
        PainelTitulo.setBackground(new Color(26,30,36));
        PainelBotoes.setBackground(new Color(26,30,36));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusBotoes = new javax.swing.ButtonGroup();
        PainelPrincipal = new javax.swing.JPanel();
        PainelTitulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PainelBotoes = new javax.swing.JPanel();
        btnAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        radioConcluido = new javax.swing.JRadioButton();
        radioNaoConcluido = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtJNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        dataEntrega = new com.toedter.calendar.JDateChooser();
        btnMenu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PainelTitulo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ALTERAR TAREFA");
        PainelTitulo.add(jLabel2);

        PainelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAlterar.setBackground(new java.awt.Color(0, 102, 102));
        btnAlterar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        PainelBotoes.add(btnAlterar);

        btnLimpar.setBackground(new java.awt.Color(0, 102, 102));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        PainelBotoes.add(btnLimpar);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STATUS :");

        StatusBotoes.add(radioConcluido);
        radioConcluido.setForeground(new java.awt.Color(255, 255, 255));
        radioConcluido.setText("CONCLUÍDO");
        radioConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioConcluidoActionPerformed(evt);
            }
        });

        StatusBotoes.add(radioNaoConcluido);
        radioNaoConcluido.setForeground(new java.awt.Color(255, 255, 255));
        radioNaoConcluido.setText(" NÃO CONCLUÍDO");
        radioNaoConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNaoConcluidoActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome da Tarefa:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descrição da Tarefa:");

        txtDescricao.setColumns(20);
        txtDescricao.setLineWrap(true);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data de Entrega:");

        btnMenu.setBackground(new java.awt.Color(0, 102, 102));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SoftwarePR/AgendaDeTarefas/Icones/Home.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID:");

        txtId.setEditable(false);
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(PainelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnMenu))
                                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                                        .addComponent(radioConcluido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioNaoConcluido)))
                                .addGap(97, 97, 97))
                            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtJNome, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(dataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(PainelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioConcluido)
                    .addComponent(radioNaoConcluido))
                .addGap(27, 27, 27)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        try{
            if(radioConcluido.isSelected()){
                STATUS =0;
            }else{
                STATUS = 1;
            }
            ID= Integer.parseInt(txtId.getText());
            NOME = txtJNome.getText();
            DESCRICAO = txtDescricao.getText();

            Date dataSelecionada = dataEntrega.getDate();

            if(dataSelecionada != null){
                SimpleDateFormat dataFormatada = new SimpleDateFormat("yyyy/MM/dd");
                DATA = dataFormatada.format(dataSelecionada);
            }else{
                DATA = "1999/01/01";
            }

            construtorCriarTarefa Tarefa = new construtorCriarTarefa();

            Tarefa.setStatus(STATUS);
            Tarefa.setNome(NOME);
            Tarefa.setDescricao(DESCRICAO);
            Tarefa.setData(DATA);
            Tarefa.setId(ID);

            conexaoBanco Banco = new conexaoBanco();
            Banco.AlterarTarefa(Tarefa);
            limparCampos();
            
            dispose();

        }catch (NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void radioConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioConcluidoActionPerformed
        verificarCheckBox();
    }//GEN-LAST:event_radioConcluidoActionPerformed

    private void radioNaoConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNaoConcluidoActionPerformed
        verificarCheckBox();
    }//GEN-LAST:event_radioNaoConcluidoActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        try{
            interfaceMenuTarefa menu = new interfaceMenuTarefa();//Chamando a Classe para o Menu
            menu.setVisible(true);//Abre a Tela de Menu
            dispose();//Fecha a Tela Atual

        }catch(Exception e){

            JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceAlterarDadosDaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceAlterarDadosDaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceAlterarDadosDaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceAlterarDadosDaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceAlterarDadosDaTarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelTitulo;
    private javax.swing.ButtonGroup StatusBotoes;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMenu;
    private com.toedter.calendar.JDateChooser dataEntrega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioConcluido;
    private javax.swing.JRadioButton radioNaoConcluido;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJNome;
    // End of variables declaration//GEN-END:variables

    private void limparCampos(){
        radioConcluido.setSelected(true);
        String caminho = "src/br/com/SoftwarePR/AgendaDeTarefas/Icones/Check_Concluido_Verde.png";
        ImageIcon iconUnchecked = new ImageIcon(caminho); 
        radioConcluido.setIcon(iconUnchecked);
        
        radioNaoConcluido.setSelected(false);
        radioNaoConcluido.setIcon(null);
        
        txtJNome.setText("");
        txtDescricao.setText("");
        dataEntrega.setDateFormatString("");
        
    }
    
    
    private void verificarCheckBox(){
        if(radioConcluido.isSelected() && !radioNaoConcluido.isSelected()){
           String caminho = "src/br/com/SoftwarePR/AgendaDeTarefas/Icones/Check_Concluido_Verde.png";
           ImageIcon iconUnchecked = new ImageIcon(caminho); 
           radioConcluido.setIcon(iconUnchecked);
           radioNaoConcluido.setSelected(false);
           radioNaoConcluido.setIcon(null);
       }else if(!radioConcluido.isSelected() && radioNaoConcluido.isSelected()){
           String caminho = "src/br/com/SoftwarePR/AgendaDeTarefas/Icones/Check_NaoConcluido_Vermelho.png";
           ImageIcon iconUnchecked = new ImageIcon(caminho); 
           radioNaoConcluido.setIcon(iconUnchecked);
           radioConcluido.setSelected(false);
           radioConcluido.setIcon(null);
       }
    }    

    public void receberDados(String id,String nome, String descricao,String data, String Status) throws ParseException{
        
        if(Status.equalsIgnoreCase("1")){
          
           
           String caminho = "src/br/com/SoftwarePR/AgendaDeTarefas/Icones/Check_NaoConcluido.png";
           ImageIcon iconUnchecked = new ImageIcon(caminho); 
           radioNaoConcluido.setIcon(iconUnchecked);
           radioConcluido.setSelected(false);
           radioConcluido.setIcon(null);
        }else{
            
            
           String caminho = "src/br/com/SoftwarePR/AgendaDeTarefas/Icones/Check_Concluido.png";
           ImageIcon iconUnchecked = new ImageIcon(caminho); 
           radioConcluido.setIcon(iconUnchecked);
           radioNaoConcluido.setSelected(false);
           radioNaoConcluido.setIcon(null);
           
            
        }
        txtId.setText(id);
        txtJNome.setText(nome);
        txtDescricao.setText(descricao);
        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
        Date date = dataFormatada.parse(data);
        dataEntrega.setDate(date);
        
        
        
        
        
    }

}
