/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.SoftwarePR.AgendaDeTarefas.Interface;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo
 */
public class interfaceMenuTarefa extends javax.swing.JFrame {

    /**
     * Creates new form interfaceMenuTarefa
     */
    public interfaceMenuTarefa() {
        initComponents();
        setLocationRelativeTo( null );//Centralizando a Tela
        PainelPrincipal.setBackground(new Color(0,102,102));
        getContentPane().setBackground(new Color(26,30,36));
        PainelBotoes.setBackground(new Color(26,30,36));
        PainelCriador.setBackground(new Color(236, 240, 241));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PainelBotoes = new javax.swing.JPanel();
        btnCriarTarefa = new javax.swing.JButton();
        btnConsultarTarefa = new javax.swing.JButton();
        btnEditarTarefa = new javax.swing.JButton();
        btnDeletarTarefa = new javax.swing.JButton();
        PainelCriador = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APP TAREFA");
        setBackground(new java.awt.Color(255, 255, 255));

        PainelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        PainelPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        PainelBotoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        btnCriarTarefa.setBackground(new java.awt.Color(0, 102, 102));
        btnCriarTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCriarTarefa.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SoftwarePR/AgendaDeTarefas/Icones/criarTarefa.png"))); // NOI18N
        btnCriarTarefa.setText("Criar Tarefa");
        btnCriarTarefa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCriarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarTarefaActionPerformed(evt);
            }
        });

        btnConsultarTarefa.setBackground(new java.awt.Color(0, 102, 102));
        btnConsultarTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultarTarefa.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SoftwarePR/AgendaDeTarefas/Icones/pesquisarTarefa.png"))); // NOI18N
        btnConsultarTarefa.setText("Consultar Tarefa");
        btnConsultarTarefa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultarTarefa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConsultarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTarefaActionPerformed(evt);
            }
        });

        btnEditarTarefa.setBackground(new java.awt.Color(0, 102, 102));
        btnEditarTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarTarefa.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SoftwarePR/AgendaDeTarefas/Icones/editarTarefaII.png"))); // NOI18N
        btnEditarTarefa.setText("Editar Tarefa");
        btnEditarTarefa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTarefaActionPerformed(evt);
            }
        });

        btnDeletarTarefa.setBackground(new java.awt.Color(0, 102, 102));
        btnDeletarTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeletarTarefa.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletarTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SoftwarePR/AgendaDeTarefas/Icones/excluirTarefa.png"))); // NOI18N
        btnDeletarTarefa.setText("Deletar Tarefa");
        btnDeletarTarefa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDeletarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarTarefaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDeletarTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnCriarTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnCriarTarefa)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarTarefa)
                .addGap(18, 18, 18)
                .addComponent(btnEditarTarefa)
                .addGap(18, 18, 18)
                .addComponent(btnDeletarTarefa)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        PainelCriador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        PainelCriador.setLayout(new java.awt.CardLayout());

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("By: Paulo Ricardo");
        PainelCriador.add(jLabel2, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PainelCriador, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelCriador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(PainelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarTarefaActionPerformed
       
        try{
            interfaceCriarTarefa criarTarefa = new interfaceCriarTarefa(); //Chama a Classe para Criar Tarefa
            criarTarefa.setVisible(true); //Abre a Tela de Criar Tarefa
            dispose();//Fecha a Janela Atual
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCriarTarefaActionPerformed

    private void btnConsultarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTarefaActionPerformed
       try{
            interfaceListarTarefa listarTarefa = new interfaceListarTarefa(); //Chama a Classe para Listar a Tarefa
            listarTarefa.setVisible(true); //Abre a Tela de Listar Tarefa
            dispose(); //Fecha a Janela Atual
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
       }
       
    }//GEN-LAST:event_btnConsultarTarefaActionPerformed

    private void btnEditarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTarefaActionPerformed
        try{
            interfaceEditarTarefa editarTarefa = new interfaceEditarTarefa(); //Chama a Classe para Editar Tarefa
            editarTarefa.setVisible(true); //Abre a Tela de Editar
            dispose();//Fecha a Tela Atual
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEditarTarefaActionPerformed

    private void btnDeletarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarTarefaActionPerformed
       try{
           interfaceDeletarTarefa deletarTarefa = new interfaceDeletarTarefa();//Chama a Classe para Deletar Tarefa
           deletarTarefa.setVisible(true);//Abre a Tela de Deletar
           dispose();//Fecha a Janela Atual
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Error: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
       }
       
    }//GEN-LAST:event_btnDeletarTarefaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceMenuTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceMenuTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceMenuTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceMenuTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceMenuTarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelCriador;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JButton btnConsultarTarefa;
    private javax.swing.JButton btnCriarTarefa;
    private javax.swing.JButton btnDeletarTarefa;
    private javax.swing.JButton btnEditarTarefa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void criarTarefa() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
