/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.SoftwarePR.AgendaDeTarefas.Interface;

import br.com.SoftwarePR.AgendaDeTarefas.Banco.conexaoBanco;
import br.com.SoftwarePR.AgendaDeTarefas.Construtor.construtorCriarTarefa;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Paulo
 */
public final class interfaceListarTarefa extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public interfaceListarTarefa() {
        initComponents();
        setLocationRelativeTo( null );//Centralizando a Tela
        aumentandoColunaTabela();
        getContentPane().setBackground(new Color(26,30,36));
        PainelTitulo.setBackground(new Color(26,30,36));
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listar Tarefa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTAR TAREFA");
        PainelTitulo.add(jLabel1);

        getContentPane().add(PainelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 580, -1));
        getContentPane().add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 330, -1));

        btnPesquisar.setBackground(new java.awt.Color(0, 102, 102));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SoftwarePR/AgendaDeTarefas/Icones/Pesquisar.png"))); // NOI18N
        btnPesquisar.setMaximumSize(new java.awt.Dimension(40, 40));
        btnPesquisar.setPreferredSize(new java.awt.Dimension(40, 40));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 40, 40));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "DESCRICAO", "DATA", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabela);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 570, 340));

        btnMenu.setBackground(new java.awt.Color(0, 102, 102));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SoftwarePR/AgendaDeTarefas/Icones/Home.png"))); // NOI18N
        btnMenu.setMaximumSize(new java.awt.Dimension(40, 40));
        btnMenu.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 40, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        carregarTarefas();
    }//GEN-LAST:event_formWindowActivated

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       carregarTarefasBusca();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        try{
            interfaceMenuTarefa menu = new interfaceMenuTarefa(); //Chamando a Classe da tela de Menu
            menu.setVisible(true);//Abre a Tela de Menu
            dispose();//Fecha a Tela Atual
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceListarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceListarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceListarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceListarTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceListarTarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelTitulo;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
    
    
    public void carregarTarefas(){
        
        conexaoBanco Banco = new conexaoBanco();
        
        List<construtorCriarTarefa> lista = Banco.ListarTarefas();
        
        DefaultTableModel dados = (DefaultTableModel) Tabela.getModel();
        
        dados.setNumRows(0);
        
        for(construtorCriarTarefa linha : lista){
            dados.addRow(new Object[]{
                linha.getId(),
                linha.getNome(),
                linha.getDescricao(),
                linha.getData(),
                linha.getStatus()
            });
            
        }
        
        
    }
    
    
    public void carregarTarefasBusca(){
        
        try{
            String busca = txtPesquisar.getText();
            conexaoBanco Banco = new conexaoBanco();

            List<construtorCriarTarefa> lista = Banco.ListarTarefasBuscar(busca);

            DefaultTableModel dados = (DefaultTableModel) Tabela.getModel();

            dados.setNumRows(0);

            for(construtorCriarTarefa linha : lista){
                dados.addRow(new Object[]{
                    linha.getId(),
                    linha.getNome(),
                    linha.getDescricao(),
                    linha.getData(),
                    linha.getStatus()
                });

            }
        
        }catch(Exception e){
            System.out.println(e);
        }
        
        
    }
    
    
    public void aumentandoColunaTabela(){
        TableColumn colunaNome = Tabela.getColumnModel().getColumn(1);
        TableColumn colunaDescricao = Tabela.getColumnModel().getColumn(2);
        TableColumn colunaData = Tabela.getColumnModel().getColumn(3);
        TableColumn colunaStatus = Tabela.getColumnModel().getColumn(3);
        colunaNome.setPreferredWidth(300);
        colunaDescricao.setPreferredWidth(500);
        colunaData.setPreferredWidth(200);
        colunaStatus.setPreferredWidth(200);
    }


}   



